#!/usr/bin/env php
<?php

set_time_limit(0);
define('HUNTER_ROOT', __DIR__);
require_once HUNTER_ROOT . '/core/Hunter.php';
$app = new Hunter\Core\App\Application();
$app->registerCommand('command', HUNTER_ROOT . '/core');
